### ISSUE TITLE
Pass in the current date into the prompt

### ISSUE THREAD

**Issue by AlanMW** [jmoney7823956789378/oobabot#5]
Hello, thanks for updating the bot to use the current API!

Is there a good place that I could throw in the current date into the prompt to let the AI know for date related questions?
I was digging through the code looking for a place to add it, but I came up short.

Everything works great by the way!

**Comment by jmoney7823956789378** [comment]
Hi, glad to hear it all works!
I've been planning a lot of prompt techniques like adding timestamps to the bot and it seems like it wouldn't be too difficult.
In order to properly conform with "llama-isms" regarding how they process numbers, I plan on using a `(5 minutes ago) [User]: Message`
format.
I'm a big noob though, so be patient :P

**Comment by jmoney7823956789378** [comment]
@AlanMW 
Hope this is ok enough :P
Might split DATE and TIME into two different template tokens if this doesnt work well.
https://github.com/jmoney7823956789378/oobabot/commit/9ae65bef095a071954f16444651be1035637098f

**Comment by jmoney7823956789378** [comment]
Darn I just realized it pulls via system time, and isn't specific for the time zone...

**Comment by AlanMW** [comment]
Thanks for adding that! It can be if you specify in `datetime.now()`. I guess TZ could be something that is defined in the cfg file if that is preferred.
